View/base.php, View/layouts/accueil.php
=> Page-accueil

View/layouts/connect.php, View/layouts/signUp.php
création du templates inscription
=> Page-inscription

View/layouts/Error.php
=> Page-erreur

Service/constantes.php, View/layouts/galerie.php, View/layouts/popupGalerie.php
ajout de la page galerie et du popup ainsi que la constante des types
=> Page-galerie

View/layouts/signUp.php
modification du select de type de photos pref sur la page inscription
=> modification du select de type de photos pref sur la page inscription

Controller/MainController.controller.php, Model/PhotoManager.php, Model/Render.php, Services/types/Photo.php, Services/types/Photographe.php
Création du crud pour les photos
- getPhotos
- getPhotosByUser
- addPhoto
- deletePhoto
- updatePhoto
=> Crud-photos

Model/CompteManager.php, Model/Model.php, Model/PhotoManager.php, index.php
Création du CRUD pour le compte:
- addUser
- updateUser
- deleteUser
- getUserInfo
=> Crud-compte

Public/style/signUp.css, Public/style/var.css, View/base.php, View/layouts/signUp.php, index.php
Ajout du style pour la page d'inscription
=> 72-ajouter-le-style-pour-la-page-dinscription

Scripts/scripts-bdd.sql
Ajout des scripts sql corriger en fonction de la colonne à ajouter
=> 53-fix-mcdmlddb

Scripts/scripts-bdd.sql
Fix des scripts de la table 'mot_de_passe'
=> Fix-scripts

Controller/MainController.controller.php, Model/CompteManager.php, Model/MessageManager.php, Model/Model.php, Model/PasswordManager.php, Model/PhotoManager.php, Model/Render.php, Services/SendMail.php, Services/types/Photo.php, Services/types/Photographe.php, index.php
=> 51-crud-mot-de-passe

Public/style/filtres.css, Public/style/galerie.css, Public/style/photoGalerie.css, View/base.php, View/layouts/filtres.php, View/layouts/galerie.php, View/layouts/photoGalerie.php
- Création du style de la page gallerie
- Création du aside pour les filtres ainsi que le style
=> 60-page-gallerie

Public/style/filtres.css, Public/style/galerie.css, Public/style/profil.css, View/base.php, View/layouts/galerie.php, View/layouts/profil.php
Création du style pour le profil de l'utilisateur
=> 59-compte-user

Controller/MainController.controller.php, Services/Router.php, index.php
Création d'un router à part de l'index
=> 52-crer-un-router

Model/CompteManager.php, Model/PasswordManager.php, Scripts/scripts-bdd.sql, Services/types/MotDePasse.php, Services/types/Photographe.php
- Correction de problèmes dans PasswordManager
- Ajout d'un nouveau type pour les mot de passes
- Correction des scripts SQL
- Prise en compte de la colonne compte_valide
=> Add-compte-valide-to-manager

Controller/MainController.controller.php, Public/style/reset.css, View/base.php, View/layouts/reset.php
Création de la page de réinitialisation du mot de passe
=> 110-page-rinitialisation-mot-de-passe

Model/PhotoManager.php, Services/constantes.php, View/layouts/filtres.php, View/layouts/signUp.php, View/layouts/upload.php
Ajout du nombre de pages dans le getPhotos et getPhotosByUser
=> 87-get-nombre-page-paginator

Controller/CompteController.php, Controller/ConnexionController.php, Controller/PasswordController.php, Model/CompteManager.php, Model/PasswordManager.php, Services/Router.php, Services/Utils.php, Services/constantes.php
Création du controller pour les utilisateurs 
Création en même temps du controller pour les connexions (#123)
=> 117-crer-le-controller-pour-luser

Controller/CompteController.php, Controller/ConnexionController.php, Controller/PasswordController.php, Model/CompteManager.php, Model/PasswordManager.php, Model/PhotoManager.php, Scripts/scripts-bdd.sql, Services/Router.php, Services/Securite.php, Services/Utils.php, Services/constantes.php, Services/types/Photographe.php, View/base.php, View/layouts/filtres.php, View/layouts/signUp.php, View/layouts/upload.php
=> Vers.back into develop

Controller/MessageController.php, Model/MessageManager.php
Création du controller pour les messages
=> 119-crer-le-controller-pour-les-messages

Controller/CompteController.php, Controller/ConnexionController.php, Controller/MessageController.php, Controller/PasswordController.php, Model/CompteManager.php, Services/SendMail.php
Ajout d'un cookie pour savoir si l'utilisateur est admin
=> 54-set-cookies

Services/Utils.php
creation de fonction permettant de valider l'email d'un compte lors de l'inscription
=> 85-validation-du-compte-par-mail
